services:
  assessment-tax:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: assessment-tax-test:test
    container_name: assessment-tax-tests
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    volumes:
      - $PWD:/src
    networks:
      - integration-test

  postgres:
    image: postgres:16
    container_name: postgres-tests
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test

networks:
  integration-test: