FROM golang:1.21-alpine AS runner
LABEL maintainer="Tanawat Hongthai <ztrixack.th@gmail.com>"

# Set the working directory outside $GOPATH to enable the support for modules.
WORKDIR /src

# Start the application
CMD ["go", "run", "main.go"]