services:
  assessment-tax:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: assessment-tax:1.0.0
    container_name: assessment-tax
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      DATABASE_URL: host=postgres port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      ADMIN_USERNAME: adminTax
      ADMIN_PASSWORD: admin!
    networks:
      - ktaxes

  postgres:
    image: postgres:16
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ktaxes'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - ktaxes

networks:
  ktaxes: