services:
  assessment-tax:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: assessment-tax:1.0.0
    container_name: assessment-tax
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      DATABASE_URL: host=postgres port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      ADMIN_USERNAME: adminTax
      ADMIN_PASSWORD: admin!
    networks:
      - ktaxes

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - ktaxes

networks:
  ktaxes: