definitions:
  github_com_ztrixack_assessment-tax_internal_handlers_tax.Allowance:
    properties:
      allowanceType:
        enum:
        - donation
        example: donation
        type: string
      amount:
        example: 0
        minimum: 0
        type: number
    required:
    - allowanceType
    type: object
  tax.CalculationsRequest:
    properties:
      allowances:
        items:
          $ref: '#/definitions/github_com_ztrixack_assessment-tax_internal_handlers_tax.Allowance'
        type: array
      totalIncome:
        example: 500000
        minimum: 0
        type: number
      wht:
        example: 0
        minimum: 0
        type: number
    type: object
  tax.CalculationsResponse:
    properties:
      tax:
        type: number
      taxRefund:
        type: number
    type: object
  tax.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact:
    email: ztrixack.th@gmail.com
    name: Tanawat Hongthai
    url: https://github.com/ztrixack/assessment-tax.git
  description: Assessment Tax API for Go Bootcamp
  title: Assessment Tax API
  version: "1.0"
paths:
  /:
    get:
      description: Hello, Go Bootcamp!
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, Go Bootcamp!
          schema:
            type: string
      summary: Hello, Go Bootcamp!
      tags:
      - system
  /tax/calculations:
    post:
      consumes:
      - application/json
      description: This endpoint calculates the tax and potentially applicable tax
        refund and tax levels based on the provided total income, withholding tax,
        and allowances.
      parameters:
      - description: Input request for tax calculation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tax.CalculationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully calculated tax and returns the tax details
          schema:
            $ref: '#/definitions/tax.CalculationsResponse'
        "400":
          description: Bad request if the input validation fails
          schema:
            $ref: '#/definitions/tax.ErrorResponse'
        "500":
          description: Internal server error if the tax calculations service fails
          schema:
            $ref: '#/definitions/tax.ErrorResponse'
      summary: Calculate Tax
      tags:
      - tax
schemes:
- http
swagger: "2.0"
